name: CI

on: [push, pull_request]

jobs:

  test:
    name: Unit Testing
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run JUnit through Maven
        run: mvn clean test

  build:
    name: Build Project
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Compile
        run: mvn clean package
      - name: Upload Build Artifact (master only)
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/upload-artifact@v1.0.0
        with:
          name: AdvanceWars-Build
          path: assembly/target/Advance-Wars-*.jar
