name: Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  make-release:
    name: Release Build
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Prevently create .m2 directory
        continue-on-error: true
        run: mkdir ~/.m2 2> /dev/null
      - name: Give git credentials to Maven
        env:
          GIT_PSW: ${{ secrets.GIT_PSW }}
        run: echo "<settings><servers><server><id>github</id><username>UlysseGuyon</username><password>${GIT_PSW}</password></server></servers></settings>" > ~/.m2/settings.xml
      - name: Setup local git email/name
        run: |
          git config user.email "ulysse.guyon@gmail.com"
          git config user.name "Ulysse Guyon"
      - name: Build project
        run: mvn -B package
      - name: Upload jar as Release asset
        run: mvn -B github-release:release
      
